// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNUnitWeb.Data;

#nullable disable

namespace MyNUnitWeb.Migrations
{
    [DbContext(typeof(AssemblyDbContext))]
    partial class AssemblyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MyNUnitWeb.Data.AssemblyData", b =>
                {
                    b.Property<int>("AssemblyDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfFailTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfIgnoredTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfSucceedTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfTest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AssemblyDataId");

                    b.ToTable("AssembliesData");
                });

            modelBuilder.Entity("MyNUnitWeb.Data.MethodData", b =>
                {
                    b.Property<int>("MethodDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssemblyDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgnoreReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSucceed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("MethodDataId");

                    b.HasIndex("AssemblyDataId");

                    b.ToTable("MethodsData");
                });

            modelBuilder.Entity("MyNUnitWeb.Data.MethodData", b =>
                {
                    b.HasOne("MyNUnitWeb.Data.AssemblyData", "AssemblyData")
                        .WithMany("MethodDatas")
                        .HasForeignKey("AssemblyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssemblyData");
                });

            modelBuilder.Entity("MyNUnitWeb.Data.AssemblyData", b =>
                {
                    b.Navigation("MethodDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
